version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "America/Los_Angeles"
      time: "06:00"
    commit-message:
      prefix: "chore"
    reviewers:
      - "microsoft/windows-drivers-rs"
    labels:
      - "type:dependabot"
      - "type:dependencies-cargo"

  - package-ecosystem: "cargo"
    directories:
      - "/crates/cargo-wdk/tests/**"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "America/Los_Angeles"
      time: "06:00"
    commit-message:
      prefix: "chore"
    reviewers:
      - "microsoft/windows-drivers-rs"
    labels:
      - "type:dependabot"
      - "type:dependencies-cargo-wdk-tests"
    groups:
      cargo-wdk-test-fixtures:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "America/Los_Angeles"
      time: "06:00"
    commit-message:
      prefix: "chore"
    reviewers:
      - "microsoft/windows-drivers-rs"
    labels:
      - "type:dependabot"
      - "type:dependencies-github-actions"
